version: '3.7'
services:
  web:
    build: .    
    env_file:
      - .env
    ports:
      - 5000:80
      - 44394:443
    volumes:
      - ${HOME}/.microsoft/usersecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID
  proxy:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

