version: '3'
services:
  db:
    image: "microsoft/mssql-server-linux"
    environment:
       SA_PASSWORD: "Ab12345678"
       ACCEPT_EULA: "Y"
    volumes:
      - ./db:/var/opt/mssql/data/
    networks:
      - app-network  
  api:
    build:
      context: LifeLike.Api
    ports:
      - 5000:80
      - 44394:443
    networks:
      - app-network
    volumes:
      - ./letsencrypt:/etc/letsencrypt:ro
      - ./www:/var/www/letsencrypt 
  proxy:
    build:
      context: LifeLike.Frontend    
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx:rw
      - ./letsencrypt:/etc/letsencrypt:rw
      - ./www:/var/www/letsencrypt 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge