version: '3'

services:
  managingconfigurationnetcore:
    environment:
      - USER_SECRETS_ID=8084c8e7-0000-0000-0000-c26798dc28d1
    ports:
      - "80"
    volumes:
      - $APPDATA/Microsoft/UserSecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID
      - $HOME/.microsoft/usersecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID