version: '3'
services:
  api:
    build:
      context: LifeLike.Api
    ports:
      - 5000:80
      - 44394:443
    networks:
      - app-network
    volumes:
      - ./letsencrypt:/etc/letsencrypt:ro
      - ./www:/var/www/letsencrypt 
  proxy:
    build:
      context: LifeLike.Frontend    
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx:rw
      - ./letsencrypt:/etc/letsencrypt:rw
      - ./www:/var/www/letsencrypt 
    networks:
      - app-network
  db:
    image: "microsoft/mssql-server-linux"
     environment:
       SA_PASSWORD: "123"
       ACCEPT_EULA: "Y"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge