version: '3'
services:
  backend:
    build:
      context: Lifelike.Frontend
    ports:
      - 5000:80
    networks:
      - app-network
  frontend:
    build:
      context: Lifelike.Frontend
    ports:
      - 4200:80
    networks:
      - app-network
  proxy:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    # links:
    #   - frontend
    #   - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge