version: '3'
services:
  db:
    image: "microsoft/mssql-server-linux"
    environment:
       SA_PASSWORD: "Ab12345678"
       ACCEPT_EULA: "Y"
    # volumes:
    #   - ./db:/var/opt/mssql/data/:rw
    networks:
      - app-network
  api:
    build:
      context: LifeLike.Api
    ports:
      - 5000:80
      # - 443:443
    networks:
      - app-network
    volumes:
      - ./letsencrypt:/etc/letsencrypt:ro
      - ./www:/var/www/letsencrypt
  frontend:
    build:
      context: LifeLike.Frontend    
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx:rw
      - ./letsencrypt:/etc/letsencrypt:rw
      - ./www:/var/www/letsencrypt 
    networks:
      - app-network
  # certbot:
  #   build:
  #     context: Certbot
  #   environment:
  #     - VIRTUAL_HOST=lifelike.pl
  #     - LETSENCRYPT_HOST=lifelike.pl
  #     - LETSENCRYPT_EMAIL=szymon@Lifelike.pl
  #   volumes:
  #     - ./letsencrypt:/etc/letsencrypt:rw
  #     - ./www:/var/www/letsencrypt
networks:
  app-network:
    driver: bridge