version: '3'
services:
  api:
    build:
      context: LifeLike.Api
    ports:
      - 5000:80
    networks:
      - app-network
  frontend:
    build:
      context: LifeLike.Frontend
    ports:
      - 4200:80
    networks:
      - app-network
  proxy:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx:rw
      - /etc/letsencrypt:/etc/letsencrypt:rw
      - ./www:/var/www/letsencrypt 
    networks:
      - app-network
networks:
  app-network:
    driver: bridge