version: '3'
volumes:
  node_modules:
services:
  # db:    
  #   container_name: db
  #   image: "microsoft/mssql-server-linux"
  #   environment:
  #      SA_PASSWORD: "Ab12345678"
  #      ACCEPT_EULA: "Y"
  #   volumes:
  #     - ./db:/var/opt/mssql/data/:rw
  #   ports:
  #     - "1433:1433"
  #   expose: 
  #     - 1433
  #   networks:
  #     - app-network
  api:
    container_name: api
    build:
      context: LifeLike.Api
    volumes:
      - ./letsencrypt:/etc/letsencrypt:ro
      - ./www:/var/www/letsencrypt
    environment:
      - frontend:http://localhost:4200
    ports:
      - "81:80"
    expose: 
      - 81
  web:
    container_name: web
    build:
      context: LifeLike.Frontend    
    ports:
      - "80:80"
    environment:
      - API:http://localhost:81
    expose:
      - 80 
    volumes:
      - node_modules:/app/node_modules

  # proxy:
  #   container_name: proxy
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   expose:
  #     - 80
  #   links:
  #     - web
  #     - api
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./logs:/var/log/nginx:rw
  #     - ./letsencrypt:/etc/letsencrypt:rw
  #     - ./www:/var/www/letsencrypt 
  # certbot:
  #   container_name: certbot
  #   build:
  #     context: Certbot
  #   environment:
  #     - VIRTUAL_HOST=lifelike.pl
  #     - LETSENCRYPT_HOST=lifelike.pl
  #     - LETSENCRYPT_EMAIL=szymon@Lifelike.pl
  #   volumes:
  #     - ./letsencrypt:/etc/letsencrypt:rw
  #     - ./www:/var/www/letsencrypt