version: '3'
services:
  api:
    build:
      context: LifeLike.Api
    ports:
      - 5000:80
    networks:
      - app-network
  proxy:
    build:
      context: LifeLike.Frontend    
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx:rw
      - ./letsencrypt:/etc/letsencrypt:rw
      - ./www:/var/www/letsencrypt 
    links:
      - api
    networks:
      - app-network
networks:
  app-network:
    driver: bridge